//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.25 at 04:42:34 PM IDT 
//


package com.exlibris.dps.alto.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Where possible, this draws from MIX's change history.
 * 
 * <p>Java class for ocrProcessingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ocrProcessingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preProcessingStep" type="{http://www.loc.gov/standards/alto/ns-v2#}processingStepType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ocrProcessingStep" type="{http://www.loc.gov/standards/alto/ns-v2#}processingStepType"/>
 *         &lt;element name="postProcessingStep" type="{http://www.loc.gov/standards/alto/ns-v2#}processingStepType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ocrProcessingType", propOrder = {
    "preProcessingStep",
    "ocrProcessingStep",
    "postProcessingStep"
})
@XmlSeeAlso({
    com.exlibris.dps.alto.xsd.Alto.Description.OCRProcessing.class
})
public class OcrProcessingType {

    protected List<ProcessingStepType> preProcessingStep;
    @XmlElement(required = true)
    protected ProcessingStepType ocrProcessingStep;
    protected List<ProcessingStepType> postProcessingStep;

    /**
     * Gets the value of the preProcessingStep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preProcessingStep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreProcessingStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingStepType }
     * 
     * 
     */
    public List<ProcessingStepType> getPreProcessingStep() {
        if (preProcessingStep == null) {
            preProcessingStep = new ArrayList<ProcessingStepType>();
        }
        return this.preProcessingStep;
    }

    /**
     * Gets the value of the ocrProcessingStep property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingStepType }
     *     
     */
    public ProcessingStepType getOcrProcessingStep() {
        return ocrProcessingStep;
    }

    /**
     * Sets the value of the ocrProcessingStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingStepType }
     *     
     */
    public void setOcrProcessingStep(ProcessingStepType value) {
        this.ocrProcessingStep = value;
    }

    /**
     * Gets the value of the postProcessingStep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postProcessingStep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostProcessingStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessingStepType }
     * 
     * 
     */
    public List<ProcessingStepType> getPostProcessingStep() {
        if (postProcessingStep == null) {
            postProcessingStep = new ArrayList<ProcessingStepType>();
        }
        return this.postProcessingStep;
    }

}
