//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.25 at 04:42:34 PM IDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/standards/alto/ns-v2#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exlibris.dps.alto.xsd;
